/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.community;

import javax.swing.JPanel;
import model.CityDirectory;

/**
 *
 * @author rahulkodate
 */
public class InsertCityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsertCityJPanel
     * 
     
     */
    
    
    JPanel WorkAreaJPanel;
    CityDirectory cityDirectory;
    
    
    
    public InsertCityJPanel(JPanel WorkAreaJPanel, CityDirectory cityDirectory) {
        initComponents();
        this.WorkAreaJPanel = WorkAreaJPanel;
        this.cityDirectory = cityDirectory;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
