/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;


import Business.Ecosystem;
import Business.Hospital.Hospital;

import Business.UserAccount.UserAccount;
import Business.city.CityDirectory;
import UserInterface.CommunityAdmin.AddCityJPanel;
import UserInterface.CommunityAdmin.CreateCommunity;
import UserInterface.HospitalAdmin.ManagePhysicianJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import UserInterface.HospitalAdmin.CreatePhysicianJPanel;

/**
 *
 * @author srushtidesai
 */
public class MedicalCareWorkAreaJpanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Ecosystem business;
    UserAccount account;
    Hospital hospital;
    CityDirectory cityDirectory;
    /**
     * Creates new form MedicalCareWorkAreaJpanel
     */
    public MedicalCareWorkAreaJpanel(JPanel userProcessContainer, UserAccount account, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account=account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftJPanel = new javax.swing.JPanel();
        hospitalPortalBtn = new javax.swing.JButton();
        manageDoctor = new javax.swing.JButton();
        btnCommunityAdmin = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        rightJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1800, 900));

        leftJPanel.setBackground(new java.awt.Color(153, 255, 153));
        leftJPanel.setMinimumSize(new java.awt.Dimension(280, 840));
        leftJPanel.setPreferredSize(new java.awt.Dimension(280, 840));
        leftJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hospitalPortalBtn.setBackground(new java.awt.Color(98, 203, 182));
        hospitalPortalBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        hospitalPortalBtn.setText("Manage Hospital ");
        hospitalPortalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalPortalBtnActionPerformed(evt);
            }
        });
        leftJPanel.add(hospitalPortalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 200, 40));

        manageDoctor.setBackground(new java.awt.Color(98, 203, 182));
        manageDoctor.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        manageDoctor.setText("Manage Doctor");
        manageDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDoctorActionPerformed(evt);
            }
        });
        leftJPanel.add(manageDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 200, 40));

        btnCommunityAdmin.setBackground(new java.awt.Color(98, 203, 182));
        btnCommunityAdmin.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnCommunityAdmin.setText("Manage Community");
        btnCommunityAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunityAdminActionPerformed(evt);
            }
        });
        leftJPanel.add(btnCommunityAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, 40));

        btnPatient.setBackground(new java.awt.Color(98, 203, 182));
        btnPatient.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnPatient.setText("Manage Patient");
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });
        leftJPanel.add(btnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 200, 40));

        rightJPanel.setBackground(new java.awt.Color(204, 255, 204));
        rightJPanel.setPreferredSize(new java.awt.Dimension(1058, 840));
        rightJPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        rightJPanel.add(jLabel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1211, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hospitalPortalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalPortalBtnActionPerformed
        // TODO add your handling code here:
        SystemAdminHospitalPortalJPanel systemAdminHospitalPortalJPanel = new SystemAdminHospitalPortalJPanel(rightJPanel, business, account);
        rightJPanel.add("SystemAdminHospitalPortalJPanel", systemAdminHospitalPortalJPanel);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_hospitalPortalBtnActionPerformed

    private void manageDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDoctorActionPerformed
        // TODO add your handling code here:
        ManageDoctorJPanel manageDoctorJPanel = new ManageDoctorJPanel(rightJPanel, business);
        rightJPanel.add("createDoctorJPanel", manageDoctorJPanel);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_manageDoctorActionPerformed

    private void btnCommunityAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunityAdminActionPerformed
        // TODO add your handling code here:
        CreateCommunity createCommunity = new CreateCommunity(rightJPanel, business, account);
        rightJPanel.add("CreateCommunity", createCommunity);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnCommunityAdminActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
        CreatePatientJPanel createPatientJPanel = new CreatePatientJPanel(rightJPanel, business);
        rightJPanel.add("CreateCommunity", createPatientJPanel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommunityAdmin;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton hospitalPortalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JButton manageDoctor;
    private javax.swing.JPanel rightJPanel;
    // End of variables declaration//GEN-END:variables
}
