/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DB4OUtil.DB4OUtil;
import Business.Ecosystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class LoginJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Ecosystem business;
    private String role;
    UserAccount user;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public LoginJPanel(JPanel userProcessContainer, Ecosystem business, String role) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.role = role;
        this.business = business;
        backgroundJPanel.setVisible(true);
        container.setVisible(false);
        leftPanel.setVisible(false);
               
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        btnLogoutLabel = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        backgroundJPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        loginJPanel = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1300, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(255, 255, 51));
        leftPanel.setMinimumSize(new java.awt.Dimension(1338, 60));
        leftPanel.setPreferredSize(new java.awt.Dimension(1338, 60));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Picture/icons8-back-64.png"))); // NOI18N
        btnLogoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogoutLabelMousePressed(evt);
            }
        });
        leftPanel.add(btnLogoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        container.setBackground(new java.awt.Color(51, 51, 51));
        container.setForeground(new java.awt.Color(31, 50, 97));
        container.setPreferredSize(new java.awt.Dimension(1338, 540));
        container.setLayout(new java.awt.CardLayout());
        add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -40, 1820, 940));

        backgroundJPanel.setBackground(new java.awt.Color(204, 255, 204));
        backgroundJPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backgroundJPanel.setFocusCycleRoot(true);
        backgroundJPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        backgroundJPanel.setPreferredSize(new java.awt.Dimension(1800, 900));
        backgroundJPanel.setRequestFocusEnabled(false);
        backgroundJPanel.setVerifyInputWhenFocusTarget(false);
        backgroundJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ui/Picture/icons8-back-arrow-24.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        backgroundJPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 30));

        loginJPanel.setBackground(new java.awt.Color(144, 234, 189));
        loginJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admin Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N
        loginJPanel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        lblUserName.setText("Username:");

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        txtPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPassword.setText("Password:");

        btnLogin.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginJPanelLayout = new javax.swing.GroupLayout(loginJPanel);
        loginJPanel.setLayout(loginJPanelLayout);
        loginJPanelLayout.setHorizontalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginJPanelLayout.createSequentialGroup()
                        .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginJPanelLayout.createSequentialGroup()
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginJPanelLayout.createSequentialGroup()
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        loginJPanelLayout.setVerticalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnLogin)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        backgroundJPanel.add(loginJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 430, 320));

        add(backgroundJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2000, 900));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        String userName = txtUserName.getText();
        char[] passwordCharArray = lblPassword.getPassword();
        String password = String.valueOf(passwordCharArray);
        
        user = business.getUserAccountDirectory().authenticateUser(userName, password);
        
        if(user != null) {
            backgroundJPanel.setVisible(false);
            container.setVisible(true);
            leftPanel.setVisible(true);
//            String greetings = "Hi";
//            greetings = greetings + " " + user.getUsername();
            container.add("workArea", 
                    user.getRole().createWorkArea(container, user, business));
//            greetingUserLabel.setText(greetings + " !!!");
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else {
           JOptionPane.showMessageDialog(null, "Please enter correct credentials");
        }
        txtUserName.setText("");
        lblPassword.setText("");

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutLabelMousePressed
        //logout();
    }//GEN-LAST:event_btnLogoutLabelMousePressed

    private void btnLogoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutLabelMouseClicked
        // TODO add your handling code here:
        dB4OUtil.storeSystem(business);
        System.out.println("clicked");
        backgroundJPanel.setVisible(true);
        container.setVisible(false);
        leftPanel.setVisible(false);
    }//GEN-LAST:event_btnLogoutLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel btnLogoutLabel;
    private javax.swing.JPanel container;
    private javax.swing.JPasswordField lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel loginJPanel;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
