package ui.Patient;

import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Patient;
import model.VitalSigns;

/**
 *
 * @author rahulkodate
 */
public class CreateVitalSign extends javax.swing.JPanel {

    /**
     * Creates new form CreateVitalSign
     */
    private Patient patient;
    private JPanel userProcessContainer;

    public CreateVitalSign(JPanel userProcessContainer, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblLanding = new javax.swing.JLabel();
    lblWeight = new javax.swing.JLabel();
    txtWeight = new javax.swing.JTextField();
    txtHeight = new javax.swing.JTextField();
    txtTemp = new javax.swing.JTextField();
    txtBoodPressure = new javax.swing.JTextField();
    lblBP = new javax.swing.JLabel();
    lblTemp = new javax.swing.JLabel();
    lblHeight = new javax.swing.JLabel();
    btnBack = new javax.swing.JButton();
    btnSave = new javax.swing.JButton();
    lblHeartRate = new javax.swing.JLabel();
    txtHeartRate = new javax.swing.JTextField();
    txtSPO2 = new javax.swing.JTextField();
    lblSPO2 = new javax.swing.JLabel();

    setBackground(new java.awt.Color(102, 153, 255));

    lblLanding.setFont(new java.awt.Font("Operator Mono", 1, 24)); // NOI18N
    lblLanding.setForeground(new java.awt.Color(255, 255, 255));
    lblLanding.setText("Encounter Details");

    lblWeight.setFont(new java.awt.Font("Operator Mono", 1, 13)); // NOI18N
    lblWeight.setForeground(new java.awt.Color(255, 255, 255));
    lblWeight.setText("Weight (lbs)");

    txtWeight.setFont(new java.awt.Font("Operator Mono", 0, 13)); // NOI18N

    txtHeight.setFont(new java.awt.Font("Operator Mono", 0, 13)); // NOI18N

    txtTemp.setFont(new java.awt.Font("Operator Mono", 0, 13)); // NOI18N

    txtBoodPressure.setFont(new java.awt.Font("Operator Mono", 0, 13)); // NOI18N

    lblBP.setFont(new java.awt.Font("Operator Mono", 1, 13)); // NOI18N
    lblBP.setForeground(new java.awt.Color(255, 255, 255));
    lblBP.setText("Blood Pressure");

    lblTemp.setFont(new java.awt.Font("Operator Mono", 1, 13)); // NOI18N
    lblTemp.setForeground(new java.awt.Color(255, 255, 255));
    lblTemp.setText("Body Temperature (Celsius)");

    lblHeight.setFont(new java.awt.Font("Operator Mono", 1, 13)); // NOI18N
    lblHeight.setForeground(new java.awt.Color(255, 255, 255));
    lblHeight.setText("Height (cms)");

    btnBack.setBackground(new java.awt.Color(51, 102, 255));
    btnBack.setFont(new java.awt.Font("Operator Mono", 1, 13)); // NOI18N
    btnBack.setForeground(new java.awt.Color(255, 255, 255));
    btnBack.setText("<- Back");
    btnBack.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBackActionPerformed(evt);
      }
    });

    btnSave.setBackground(new java.awt.Color(51, 102, 255));
    btnSave.setFont(new java.awt.Font("Operator Mono", 1, 13)); // NOI18N
    btnSave.setForeground(new java.awt.Color(255, 255, 255));
    btnSave.setText("Save");
    btnSave.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSaveActionPerformed(evt);
      }
    });

    lblHeartRate.setFont(new java.awt.Font("Operator Mono", 1, 13)); // NOI18N
    lblHeartRate.setForeground(new java.awt.Color(255, 255, 255));
    lblHeartRate.setText("Heart Rate");

    txtHeartRate.setFont(new java.awt.Font("Operator Mono", 0, 13)); // NOI18N

    txtSPO2.setFont(new java.awt.Font("Operator Mono", 0, 13)); // NOI18N

    lblSPO2.setFont(new java.awt.Font("Operator Mono", 1, 13)); // NOI18N
    lblSPO2.setForeground(new java.awt.Color(255, 255, 255));
    lblSPO2.setText("Oxygen Saturation");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(187, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(124, 124, 124)
                .addComponent(lblLanding)
                .addGap(141, 141, 141))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTemp)
                    .addComponent(lblHeight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblWeight, javax.swing.GroupLayout.Alignment.TRAILING))
                  .addComponent(lblBP))
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(txtBoodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(lblHeartRate)
                  .addComponent(lblSPO2))
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(txtSPO2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(234, 234, 234))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(425, 425, 425))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblLanding)
          .addComponent(btnBack))
        .addGap(29, 29, 29)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblWeight)
          .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblHeight)
          .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblTemp)
          .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblBP)
          .addComponent(txtBoodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblHeartRate)
          .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblSPO2)
          .addComponent(txtSPO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
        .addComponent(btnSave)
        .addGap(212, 212, 212))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            double weight = Double.parseDouble(txtWeight.getText());
            double height = Double.parseDouble(txtHeight.getText());
            double temp = Double.parseDouble(txtTemp.getText());
            double bp = Double.parseDouble(txtBoodPressure.getText());
            double heartRate = Double.parseDouble(txtHeartRate.getText());
            double spo2 = Double.parseDouble(txtSPO2.getText());

            VitalSigns vs = patient.getVitalSignsHistory().addVitalSigns();
            vs.setWeight(weight);
            vs.setHeight(height);
            vs.setTemperature(temp);
            vs.setBloodPressure(bp);
            vs.setHeartRate(heartRate);
            vs.setOxygenSaturation(spo2);
            vs.setTime(new Date());
            JOptionPane.showMessageDialog(this, "Vital signs added succssfully!", "Update",
                    JOptionPane.INFORMATION_MESSAGE);
            clearFields();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter valid values!", "Error", JOptionPane.ERROR_MESSAGE);
        }
  }//GEN-LAST:event_btnSaveActionPerformed

  private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
  }//GEN-LAST:event_btnBackActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnBack;
  private javax.swing.JButton btnSave;
  private javax.swing.JLabel lblBP;
  private javax.swing.JLabel lblHeartRate;
  private javax.swing.JLabel lblHeight;
  private javax.swing.JLabel lblLanding;
  private javax.swing.JLabel lblSPO2;
  private javax.swing.JLabel lblTemp;
  private javax.swing.JLabel lblWeight;
  private javax.swing.JTextField txtBoodPressure;
  private javax.swing.JTextField txtHeartRate;
  private javax.swing.JTextField txtHeight;
  private javax.swing.JTextField txtSPO2;
  private javax.swing.JTextField txtTemp;
  private javax.swing.JTextField txtWeight;
  // End of variables declaration//GEN-END:variables

    private void clearFields() {
        txtBoodPressure.setText("");
        txtHeartRate.setText("");
        txtHeight.setText("");
        txtSPO2.setText("");
        txtTemp.setText("");
        txtWeight.setText("");
    }
}
