/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.Doctor.Doctor;
import Business.Ecosystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PhysicianRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rahulkodate
 */
public class PatientUpcomingAppointmentsJPanel extends javax.swing.JPanel {
    
    JPanel CardLayoutJPanel;
    UserAccount account;
    Ecosystem business;

    /**
     * Creates new form PatientUpcomingAppointmentsJPanel
     */
    public PatientUpcomingAppointmentsJPanel(JPanel CardLayoutJPanel, UserAccount account, Ecosystem business) {
        initComponents();
        
        this.CardLayoutJPanel = CardLayoutJPanel;
        this.business = business;
        this.account = account;
        
        this.populateTable();
        
    }

    public void populateTable() {
        // populate all patients in patient directory
        ArrayList<WorkRequest> appointmentList = account.getWorkQueue().getWorkRequestList();
        ArrayList<WorkRequest> upcomingAppointmentList = new ArrayList();
        for(WorkRequest w: appointmentList) {
            if(!w.getStatus().equals("complete")) {
                upcomingAppointmentList.add(w);
            }
        }
        
    
        int rowCount = UpcomingAppointmentsJTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)UpcomingAppointmentsJTable.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(WorkRequest w: upcomingAppointmentList) {
            Object row[] = new Object[7];
            
            PhysicianRequest pr = (PhysicianRequest) w;        
            Doctor doctor = (Doctor) w.getReceiver().getDetails();
          
            
            row[0] = doctor.getName();
            row[1] = doctor.getHospital().getName();
            row[2] = doctor.getCommunity().getName();
            row[3] = pr;
            row[4] = pr.getStatus();
            row[5] = pr.getTime();
            row[6] = doctor.getHospital().getCommunity().getCity();
            
            model.addRow(row);
            
            
        }     
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpcomingAppointmentsJPanel = new javax.swing.JPanel();
        lblUpcomingAppointments = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        UpcomingAppointmentsJTable = new javax.swing.JTable();
        btnCancelAppointment = new javax.swing.JButton();

        UpcomingAppointmentsJPanel.setBackground(new java.awt.Color(0, 105, 255));
        UpcomingAppointmentsJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUpcomingAppointments.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        lblUpcomingAppointments.setForeground(new java.awt.Color(255, 255, 255));
        lblUpcomingAppointments.setText("UPCOMING APPOINTMENTS");
        UpcomingAppointmentsJPanel.add(lblUpcomingAppointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, 58));

        UpcomingAppointmentsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Physician", "Hospital", "Community", "Date Requested", "Status", "Time Slot", "Address"
            }
        ));
        jScrollPane4.setViewportView(UpcomingAppointmentsJTable);

        UpcomingAppointmentsJPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 700, 183));

        btnCancelAppointment.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnCancelAppointment.setText("Cancel  Appointment");
        btnCancelAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAppointmentActionPerformed(evt);
            }
        });
        UpcomingAppointmentsJPanel.add(btnCancelAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 210, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(UpcomingAppointmentsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpcomingAppointmentsJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAppointmentActionPerformed
        // TODO add your handling code here:
        
        int rowCount = UpcomingAppointmentsJTable.getSelectedRow();
        
        if(rowCount < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        
        WorkRequest request = (WorkRequest) UpcomingAppointmentsJTable.getValueAt(rowCount, 3);
        request.setStatus("patient canceled");
        
        // delete from patient work queue
        this.account.getWorkQueue().getWorkRequestList().remove(request);
        
        
        // delete from physician work queue
        request.getReceiver().getWorkQueue().getWorkRequestList().remove(request);
        
        JOptionPane.showMessageDialog(null, "Appointment deleted");
        
    }//GEN-LAST:event_btnCancelAppointmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UpcomingAppointmentsJPanel;
    private javax.swing.JTable UpcomingAppointmentsJTable;
    private javax.swing.JButton btnCancelAppointment;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblUpcomingAppointments;
    // End of variables declaration//GEN-END:variables
}
