/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Patient;

import Business.Patient.Patient;
import Business.Patient.PatientDetails;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Saad Ghojaria
 */
public class PatientDetailsJPanel extends javax.swing.JPanel {
    
    private JPanel CardLayoutJPanel;
    private PatientDetails details;
    private UserAccount account;

    /** Creates new form PatientDetailsJPanel */
    public PatientDetailsJPanel(JPanel CardLayoutJPanel, PatientDetails details, UserAccount account) {
        initComponents();
        
        this.CardLayoutJPanel = CardLayoutJPanel;
        this.details = details;
        this.account = account;
        
        if(account.getRole().toString().equals("Business.Role.PhysicianRole")) {
            addNotesBtn.setVisible(true);
            saveBtn.setVisible(true);
            
            addNotesBtn.setEnabled(true);
            saveBtn.setEnabled(false);
            
        } else {
            
            addNotesBtn.setVisible(false);
            saveBtn.setVisible(false);
        }
        
        
        this.dateTxt.setText(details.getDate().toString());
         this.hospitalTxt.setText((details.getDoctor() != null ? details.getDoctor().getHospital().getCommunity().getName() :"Hospital Dummy" ));
      
        this.DoctorTxt.setText((details.getDoctor() != null ) ? details.getDoctor().getName() : "Doctor Dummy");
        this.notesTxt.setText(details.getNotes());
        
        this.notesTxt.setLineWrap(true);
        
        this.dateTxt.setEnabled(false);
        this.hospitalTxt.setEnabled(false);
        this.DoctorTxt.setEnabled(false);
        this.notesTxt.setEnabled(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hospitalTxt = new javax.swing.JTextField();
        DoctorTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesTxt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        addNotesBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(hospitalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 382, -1));
        add(DoctorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 382, -1));
        add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 382, -1));

        notesTxt.setColumns(20);
        notesTxt.setRows(5);
        jScrollPane1.setViewportView(notesTxt);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 382, 214));

        jLabel1.setText("Hospital: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel2.setText("Physician: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel3.setText("Date: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel4.setText("Notes: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        backBtn.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, -1));

        addNotesBtn.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        addNotesBtn.setText("Add Notes");
        addNotesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNotesBtnActionPerformed(evt);
            }
        });
        add(addNotesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        saveBtn.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 430, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardLayoutJPanel.remove(this);
        CardLayout layout = (CardLayout) CardLayoutJPanel.getLayout();
        layout.previous(CardLayoutJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addNotesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNotesBtnActionPerformed
        // TODO add your handling code here:
        notesTxt.setEnabled(true);
        saveBtn.setEnabled(true);
        addNotesBtn.setEnabled(false);
    }//GEN-LAST:event_addNotesBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        notesTxt.setEnabled(false);
        saveBtn.setEnabled(false);
        addNotesBtn.setEnabled(true);
        
        this.details.setNotes(notesTxt.getText());
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DoctorTxt;
    private javax.swing.JButton addNotesBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextField hospitalTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea notesTxt;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables

}
