/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Physician;

import UserInterface.HospitalAdmin.*;

import Business.Doctor.Doctor;
import UserInterface.SystemAdmin.*;
import Business.Ecosystem;
import Business.Hospital.Hospital;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rahulkodate
 */
public class DoctorSideNavWorkAreaJpanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Ecosystem business;
    UserAccount account;
    Hospital hospital;
    Doctor doctor;
    /**
     * Creates new form MedicalCareWorkAreaJpanel
     */
    public DoctorSideNavWorkAreaJpanel(JPanel userProcessContainer, UserAccount account, 
             Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account = account;
        this.doctor = (Doctor) account.getDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftJPanel = new javax.swing.JPanel();
        btnAppointments = new javax.swing.JButton();
        btnPatientHistory = new javax.swing.JButton();
        btnPersonalInformation = new javax.swing.JButton();
        rightJPanel = new javax.swing.JPanel();
        systemAdminPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1800, 900));

        leftJPanel.setBackground(new java.awt.Color(172, 255, 172));
        leftJPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leftJPanel.setMinimumSize(new java.awt.Dimension(280, 840));
        leftJPanel.setPreferredSize(new java.awt.Dimension(280, 840));
        leftJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAppointments.setBackground(new java.awt.Color(98, 203, 182));
        btnAppointments.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAppointments.setText("Appointments");
        btnAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentsActionPerformed(evt);
            }
        });
        leftJPanel.add(btnAppointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, 40));

        btnPatientHistory.setBackground(new java.awt.Color(98, 203, 182));
        btnPatientHistory.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnPatientHistory.setText("Patient History");
        btnPatientHistory.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPatientHistory.setMinimumSize(new java.awt.Dimension(200, 40));
        btnPatientHistory.setPreferredSize(new java.awt.Dimension(200, 40));
        btnPatientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientHistoryActionPerformed(evt);
            }
        });
        leftJPanel.add(btnPatientHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btnPersonalInformation.setBackground(new java.awt.Color(98, 203, 182));
        btnPersonalInformation.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnPersonalInformation.setText("Personal Information");
        btnPersonalInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInformationActionPerformed(evt);
            }
        });
        leftJPanel.add(btnPersonalInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, 40));

        rightJPanel.setBackground(new java.awt.Color(204, 255, 204));
        rightJPanel.setPreferredSize(new java.awt.Dimension(1058, 840));
        rightJPanel.setLayout(new java.awt.CardLayout());

        systemAdminPanel.setBackground(new java.awt.Color(204, 255, 204));
        systemAdminPanel.setMinimumSize(new java.awt.Dimension(1338, 840));

        javax.swing.GroupLayout systemAdminPanelLayout = new javax.swing.GroupLayout(systemAdminPanel);
        systemAdminPanel.setLayout(systemAdminPanelLayout);
        systemAdminPanelLayout.setHorizontalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1338, Short.MAX_VALUE)
        );
        systemAdminPanelLayout.setVerticalGroup(
            systemAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        rightJPanel.add(systemAdminPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 2446, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientHistoryActionPerformed
        SearchJPanel searchJPanel = new SearchJPanel(rightJPanel, this.doctor, this.account, business);
        rightJPanel.add("SearchPatientJPanel", searchJPanel);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel); 
    }//GEN-LAST:event_btnPatientHistoryActionPerformed

    private void btnAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentsActionPerformed
        // TODO add your handling code here:
        PhysicianAppointmentsJPanel physicianAppointmentsJPanel = new PhysicianAppointmentsJPanel(rightJPanel, account, business);
        rightJPanel.add("PhysicianAppointmentsJPanel", physicianAppointmentsJPanel);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnAppointmentsActionPerformed

    private void btnPersonalInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInformationActionPerformed
        // TODO add your handling code here:
        PhysicianInfoJPanel physicianInfoJPanel = new PhysicianInfoJPanel(rightJPanel, this.doctor);
        rightJPanel.add("PhysicianInfoJPanel", physicianInfoJPanel);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel); 
    }//GEN-LAST:event_btnPersonalInformationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointments;
    private javax.swing.JButton btnPatientHistory;
    private javax.swing.JButton btnPersonalInformation;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JPanel rightJPanel;
    private javax.swing.JPanel systemAdminPanel;
    // End of variables declaration//GEN-END:variables
}
